package com.arashafsharpour.daresaymovie.features.moviedetail.infrastracture

import com.arashafsharpour.daresaymovie.infrastructure.coordinator.ICoordinator

interface IMovieDetailCoordinator : ICoordinator