disabled_rules: 
  - vertical_parameter_alignment

opt_in_rules: 
  - empty_count

included: 
  - Movie

shorthand_operator: warning
# vertical_parameter_alignment: warning
multiple_closures_with_trailing_closure: warning

function_body_length: 
  - 100 # warning
  - 300 # error

force_cast: warning 
force_try:
  severity: warning 

line_length: 300

type_body_length:
  - 400 # warning
  - 1500 # error

file_length:
  warning: 500
  error: 1000

type_name:
  min_length: 2 # warning
  max_length: # error
    warning: 50
    error: 60

identifier_name:
  min_length: 2
  #max_length: # only min_length
  #  error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" 
