# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Nuke'

  target 'MovieTests' do
    inherit! :search_paths
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
  end

end
