package se.bynumbers.daresayweather.util

class Constants {
    //weather.id (from Open->icon
    companion object {
        const val WEATHER_URL = "https://worksample-api.herokuapp.com/weather"
        const val SP_DARESAY_WEATHER = "SP_DARESAY_WEATHER"
        const val SP_LOCATION_ENABLED = "SP_LOCATION_ENABLED"
        const val SP_FAHRENHEIT = "SP_FAHRENHEIT"
        const val API_KEY = "api-key"
        val weatherIconMap: HashMap<String, String> = hashMapOf(
            "201d" to "wi_day_thunderstorm",
            "201n" to "wi_night_alt_thunderstorm",
            "202d" to "wi_day_thunderstorm",
            "202n" to "wi_night_alt_thunderstorm",
            "210d" to "wi_day_thunderstorm",
            "210n" to "wi_night_alt_thunderstorm",
            "211d" to "wi_day_thunderstorm",
            "211n" to "wi_night_alt_thunderstorm",
            "212d" to "wi_day_thunderstorm",
            "212n" to "wi_night_alt_thunderstorm",
            "221d" to "wi_day_thunderstorm",
            "221d" to "wi_night_alt_thunderstorm",
            "230d" to "wi_day_thunderstorm",
            "230n" to "wi_night_alt_thunderstorm",
            "231d" to "wi_day_thunderstorm",
            "231n" to "wi_night_alt_thunderstorm",
            "232d" to "wi_day_thunderstorm",
            "232n" to "wi_night_alt_thunderstorm",

            "300d" to "wi_day_sprinkle",
            "300n" to "wi_night_sprinkle",
            "301d" to "wi_day_sprinkle",
            "301n" to "wi_night_sprinkle",
            "302d" to "wi_day_rain",
            "302n" to "wi_night_rain",
            "310d" to "wi_day_rain",
            "310n" to "wi_night_rain",
            "311d" to "wi_day_rain",
            "311n" to "wi_night_rain",
            "312d" to "wi_day_rain",
            "312n" to "wi_night_rain",
            "313d" to "wi_day_showers",
            "313n" to "wi_night_showers",
            "314d" to "wi_day_showers",
            "314n" to "wi_night_showers",
            "321d" to "wi_rain",
            "321n" to "wi_night_rain",

            "500d" to "wi_day_sprinkle",
            "500n" to "wi_night_sprinkle",
            "501d" to "wi_day_sprinkle",
            "501n" to "wi_night_sprinkle",
            "502d" to "wi_rain",
            "502n" to "wi_night_rain",
            "503d" to "wi_rain",
            "503n" to "wi_night_rain",
            "504d" to "wi_rain",
            "504n" to "wi_night_rain",
            "511d" to "wi_hail",
            "511n" to "wi_night_hail",
            "520d" to "wi_day_showers",
            "520n" to "wi_night_showers",
            "521d" to "wi_day_showers",
            "522n" to "wi_night_showers",
            "531d" to "wi_day_showers",
            "531n" to "wi_night_showers",

            "600d" to "wi_day_snow",
            "600n" to "wi_night_alt_snow",
            "601d" to "wi_day_snow",
            "601n" to "wi_night_alt_snow",
            "602d" to "wi_day_snow",
            "602n" to "wi_night_alt_snow",
            "611d" to "wi_day_sleet",
            "611n" to "wi_night_alt_sleet",
            "612d" to "wi_day_sleet",
            "612n" to "wi_night_alt_sleet",
            "613d" to "wi_day_sleet",
            "613n" to "wi_night_alt_sleet",
            "615d" to "wi_day_sleet",
            "615n" to "wi_night_alt_sleet",
            "616d" to "wi_day_sleet",
            "616n" to "wi_night_alt_sleet",
            "620d" to "wi_day_snow",
            "620n" to "wi_night_alt_snow",
            "621d" to "wi_day_snow",
            "621n" to "wi_night_alt_snow",
            "622d" to "wi_day_snow",
            "622n" to "wi_night_alt_snow",

            "701d" to "wi_fog",
            "701n" to "wi_night_fog",
            "711d" to "wi_fog",
            "711n" to "wi_night_fog",
            "721d" to "wi_fog",
            "721n" to "wi_night_fog",
            "731d" to "wi_fog",
            "731n" to "wi_night_fog",
            "741d" to "wi_fog",
            "741n" to "wi_night_fog",
            "751d" to "wi_fog",
            "751n" to "wi_night_fog",
            "761d" to "wi_fog",
            "761n" to "wi_night_fog",
            "762d" to "wi_fog",
            "762n" to "wi_night_fog",
            "771d" to "wi_fog",
            "771n" to "wi_night_fog",
            "781d" to "wi_day_rain_wind",
            "781n" to "wi_night_rain_wind",

            "800d" to "wi_day_sunny",
            "800n" to "wi_night_clear",
            "801d" to "wi_day_cloudy_high",
            "801n" to "wi_night_cloudy_high",
            "802d" to "wi_day_cloudy_high",
            "802n" to "wi_night_cloudy_high",
            "803d" to "wi_day_cloudy",
            "803n" to "wi_night_cloudy",
            "804d" to "wi_day_sunny_overcast",
            "804n" to "wi_night_cloudy_high",
            "na" to "wi_na"
        )
    }
}