# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DareMovie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Nuke', '~> 9.4'

  target 'DareMovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DareMovieUITests' do
    # Pods for testing
  end

end
