package com.arashafsharpour.daresaymovie.features.reviews.infrastracture

import com.arashafsharpour.daresaymovie.infrastructure.coordinator.ICoordinator

interface IReviewsListCoordinator : ICoordinator